name: Deploy

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY: ${{github.ref == 'refs/heads/master'}}
      REF: ${{github.ref}}

    steps:
      - run: |
          echo $DEPLOY
          echo $REF
          echo $GITHUB_REF
          echo ${{github.ref}}
